# _config.yml

title: QuratulAin
description: A showcase of my work and projects
url: https://QuratulAin20.github.io
baseurl: ""  # Leave as is for the root domain

# Author information
author:
  name: Quratul Ain
  email: qain_28@outlook.com
  github: https://github.com/QuratulAin20
  

# Build settings
markdown: kramdown
theme: minima  # You can change this to any other Jekyll theme

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Social media links
social:
  - icon: fab fa-github
    link: https://github.com/QuratulAin20
  - icon: fab fa-linkedin
    link: https://linkedin.com/in/Quratul Ain


# Portfolio settings
#portfolio:
  #projects:
    #- title: Project One
     # description: A brief description of Project One.
      #link: https://github.com/yourusername/project-one
      #image: /assets/images/project-one.png

    #- title: Project Two
     # description: A brief description of Project Two.
      #link: https://github.com/yourusername/project-two
      #image: /assets/images/project-two.png

    #- title: Project Three
     # description: A brief description of Project Three.
      #link: https://github.com/yourusername/project-three
      #image: /assets/images/project-three.png
